# dev/replicas.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: mywebapp
          image: myrepo/mywebapp:latest
